[toolchain]
channel = "1.91.1"
profile = "minimal"
components = [ "rustfmt", "clippy", "rust-analyzer", "rust-src", "cargo", "rustc" ]
targets = [
    "wasm32-wasip2", # extensions
    "x86_64-unknown-linux-musl", # remote server
]
